site_name: BuildingOS Documentation
site_description: Docs-as-Code for the BuildingOS platform
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
plugins:
  - search
  - tags
  - mermaid2
nav:
  - Overview: docs/README.md
  - Governance: docs/governance/README.md
  - ADRs: docs/adr/README.md
  - C4: docs/c4/README.md
  - Architecture: docs/architecture/README.md
  - Agents: docs/agents/README.md
  - APIs:
      - Overview: docs/apis/README.md
      - HTTP (OpenAPI): docs/apis/http/openapi.yaml
      - Events (AsyncAPI): docs/apis/events/asyncapi.yaml
  - Data: docs/data/README.md
  - Infra: docs/infra/README.md
  - Observability: docs/observability/README.md
  - Security: docs/security/README.md
  - Operations: docs/operations/README.md
  - Testing: docs/testing/README.md

